{
  try {
    return await0(timeoutMillis,false);
  }
 catch (  InterruptedException e) {
    throw new InternalError();
  }
}
